name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm install
        run: npm ci
      - name: run the unit tests
        run: npm test
      - name: Publish the image to GitHub Container Registry
        run: |
          docker login --username blackhat955 --password ${{ secrets.ACCESS_TOKEN }} ghcr.io
          docker build -t ghcr.io/blackhat955/arithmetic-service:1 --file Dockerfile .
          docker push ghcr.io/blackhat955/arithmetic-service:1
          
      - name: Publish the image to Azure Container Registry
        run: |
          docker login --username practicum16durgesh --password ${{ secrets.AZURE_CONTAINER_REGISTRY }} practicum16durgesh.azurecr.io
          docker tag ghcr.io/blackhat955/arithmetic-service:1 practicum16durgesh.azurecr.io/arithmetic-service:1
          docker push practicum16durgesh.azurecr.io/arithmetic-service:1
          
